### ISSUE TITLE
Discription of Line weight

### ISSUE THREAD

**Issue by JahanviSapoliya** [halfmonty/StringArtGenerator#7]
What is line weight? how is it converted to real thread's thickness?

**Comment by benyamin99** [comment]
Yes, what is the use of this line weight ??? And what is the radius of the circle in reality? Answer my two questions as soon as possible @halfmonty @JahanviSapoliya 
![Screenshot (39)](https://user-images.githubusercontent.com/77739702/105199276-d8a46e00-5b53-11eb-95c9-7971112a074c.png)

**Comment by halfmonty** [comment]
To explain the Line Weight I'll have to explain a bit about how the algorithm works. The way the algorithm works is, for it to determine where to draw a line/string it checks the pixel value of the source image between each possible pin to determine which is the darkest and then it draws a line. The line weight is the value that is subtracted from the source image's pixels. You have to subtract some value or else the same line will always be considered the darkest each time you run the algorithm. 

Each pixel has a maximum possible darkness value of 255, so a line weight of 20 means that when the algorithm draws a line over a certain pixel, it subtracts 20 from the value, so 255 becomes 235, meaning that a completely black area of a picture will take about 12-13 lines overlapping to represent because 255 / 20 is 12.75. Realistically you don't tend to get that much overlapping because as you draw lines and subtract the line weight, other areas of the picture become the next darkest. So this line weight doesn't represent any real world value but it can be tweaked in order to better represent reality.

For example if you were to make a very large string art ring and use a very thin string, a line weight of 20 might be too high of a value that your resulting image would be too see-through and the dark areas of the string art wouldn't be dark enough. You could then tweak this line weight to be a smaller number to cause the algorithm to use more lines/string to represent dark areas.

Should you need to tweak this number? Idk, but that goes into your next question "What is the radius of the circle in reality". I don't know precisely. What I did when I made this generator was do my best to match the results of the guy who inspired me to make this, which you can find here: https://www.reddit.com/r/DIY/comments/au0ilz/made_a_string_art_portrait_out_of_a_continuous_2/ 

He appears to be using a circle about the size of a bicycle tire. The line weight I chose and other defaults of this generator were more or less arbitrarily chosen by me to match the results in that reddit post with a radius of about a bicycle wheel with standard thread. I made them variable in case you want to make something bigger or smaller or use thicker or thinner string. As for how much exactly you should change those variables, that's up to you.
